
const websiteConfig = {

youtubeVideo: "https://youtu.be/wDchsz8nmbo",

sectionB: [
["1","COPIES OF AFFILIATION/UPGRADATION LETTER AND RECENT EXTENSION OF AFFILIATION, IF ANY","01_affiliation_letter.pdf"],
["2","COPIES OF SOCIETIES/TRUST/COMPANY REGISTRATION/RENEWAL CERTIFICATE, AS APPLICABLE","02_society_registration.pdf"],
["3","COPY OF NO OBJECTION CERTIFICATE (NOC) ISSUED, IF APPLICABLE, BY THE STATE GOVT./UT","03_noc_certificate.pdf"],
["4","COPIES OF RECOGNITION CERTIFICATE UNDER RTE ACT, 2009, AND IT’S RENEWAL IF APPLICABLE","04_recognition_certificate_rte.pdf"],
["5","COPY OF VALID BUILDING SAFETY CERTIFICATE AS PER THE NATIONAL BUILDING CODE","05_building_safety_certificate.pdf"],
["6","COPY OF VALID FIRE SAFETY CERTIFICATE ISSUED BY THE COMPETENT AUTHORITY","06_fire_safety_certificate.pdf"],
["7","COPY OF THE SELF CERTIFICATION SUBMITTED BY THE SCHOOL FOR AFFILIATION/UPGRADATION/EXTENSION OF AFFILIATION","07_self_certification.pdf"],
["8","COPIES OF VALID WATER, HEALTH AND SANITATION CERTIFICATES","08_water_health_sanitation.pdf"]
],

sectionC: [
["1","FEE STRUCTURE OF THE SCHOOL","09_fee_structure.pdf"],
["2","ANNUAL ACADEMIC CALENDER","10_academic_calendar.pdf"],
["3","LIST OF SCHOOL MANAGEMENT COMMITTEE (SMC)","11_smc_list.pdf"],
["4","LIST OF PARENTS TEACHERS ASSOCIATION (PTA) MEMBERS","12_pta_members.pdf"],
["5","LAST THREE-YEAR RESULT OF THE BOARD EXAMINATION AS PER APPLICABILITY","13_board_exam_results.pdf"]
]

};
